language: node_js
node_js:
- "4"

sudo: false

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_96258599e233_key -iv $encrypted_96258599e233_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name 'xcatliu'
  - git config --global user.email 'xcatliu@gmail.com'

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy
